Update BakaXL_4.0.yml

diff --git a/.github/workflows/BakaXL_4.0.yml b/.github/workflows/BakaXL_4.0.yml
--- a/.github/workflows/BakaXL_4.0.yml
+++ b/.github/workflows/BakaXL_4.0.yml
@@ -38,6 +38,54 @@ jobs:
           user_repo: "${{ secrets.GITLAB_USER }}"
           pass_repo: "${{ secrets.GITLAB_TOKEN }}"
           url_repo: "${{ secrets.GITLAB_BAKAXL_V4_GIT }}"
+          
+      - name: Get last commit ID artifact
+        id: get-commit-artifact
+        run: |
+          # Attempt to download the artifact from the last run
+          mkdir -p artifacts
+          if ! curl -o artifacts/last_commit_id.txt -L "${{ secrets.GITHUB_API_URL }}/repos/${{ github.repository }}/actions/artifacts/${{ secrets.LAST_COMMIT_ARTIFACT_ID }}/zip" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"; then
+            echo "Artifact not found, assuming first run."
+          fi
+  
+      - name: Get last commit ID
+        id: get-last-commit
+        run: |
+          if [ -f artifacts/last_commit_id.txt ]; then
+            LAST_COMMIT_ID=$(cat artifacts/last_commit_id.txt)
+          else
+            LAST_COMMIT_ID=""
+          fi
+          echo "Last commit ID: $LAST_COMMIT_ID"
+          echo "::set-output name=last_commit_id::$LAST_COMMIT_ID"
+  
+      - name: Get current commit ID
+        id: get-current-commit
+        run: |
+          cd bakaxl-rs
+          CURRENT_COMMIT_ID=$(git rev-parse HEAD)
+          echo "Current commit ID: $CURRENT_COMMIT_ID"
+          echo "::set-output name=current_commit_id::$CURRENT_COMMIT_ID"
+
+      - name: Save current commit ID
+        run: |
+          echo "${{ steps.get-current-commit.outputs.current_commit_id }}" > current_commit_id.txt
+
+      # 构建前获取构建信息
+      - name: Check BuildInfo
+        run: |
+          cd bakaxl-rs
+          
+          git log ${{ steps.get-last-commit.outputs.last_commit_id }}..HEAD --pretty=format:'{"Author": "%an", "Comment": "%s", "Date": "%ad", "TimeStamp": %at000, "CommitID": "%H"},' --date=format:'%Y-%m-%d %H:%M:%S %z' > ./Public/Commits.txt
+          echo "[" > ./Public/Commits.json
+          sed '$ s/,$//' Commits.txt >> ./Public/Commits.json
+          echo "]" >> ./Public/Commits.json
+          cat ./Public/Commits.json
+
+          BUILD_TIME=$(date -u +%s)
+          JSON_CONTENT=$(jq -n --arg channel "Bunny" --arg buildtime "$BUILD_TIME" '{Channel: $channel, BuildTime: $buildtime}')
+          echo "$JSON_CONTENT" > ./Public/BuildInfo.json
+          cat ./Public/BuildInfo.json
 
       - name: setup node
         uses: actions/setup-node@v3
@@ -95,12 +143,31 @@ jobs:
         with:
           name: BakaXL 4.0 Windows
           path: |
-            bakaxl-rs/src-tauri/target/release/bundle
             bakaxl-rs/src-tauri/target/release/BakaXL.exe
             
-      - name: Upload Artifact (macos and linux only)
-        if: matrix.platform != 'windows-latest'
+      - name: Upload Artifact (macos)
+        if: matrix.platform == 'macos-latest'
         uses: actions/upload-artifact@v3
         with:
-          name: BakaXL 4.0 Other
+          name: BakaXL 4.0 MacOS
           path: bakaxl-rs/src-tauri/target/release/bundle
+      
+      - name: Upload Artifact (Debian)
+        if: matrix.platform == 'ubuntu-latest'
+        uses: actions/upload-artifact@v3
+        with:
+          name: BakaXL 4.0 Debian
+          path: bakaxl-rs/src-tauri/target/release/bundle/deb/*.deb
+
+      - name: Upload Artifact (Linux)
+        if: matrix.platform == 'ubuntu-latest'
+        uses: actions/upload-artifact@v3
+        with:
+          name: BakaXL 4.0 Linux
+          path: bakaxl-rs/src-tauri/target/release/bundle/appimage/*.AppImage
+
+      - name: Upload current commit ID as artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: last_commit_id
+          path: current_commit_id.txt
